/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace FileRegistry {
  export type FileRecordStruct = {
    cid: string;
    name: string;
    timestamp: BigNumberish;
  };

  export type FileRecordStructOutput = [
    cid: string,
    name: string,
    timestamp: bigint
  ] & { cid: string; name: string; timestamp: bigint };
}

export interface FileRegistryInterface extends Interface {
  getFunction(nameOrSignature: "addFile" | "getMyFiles"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "FileAdded"): EventFragment;

  encodeFunctionData(
    functionFragment: "addFile",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getMyFiles",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "addFile", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getMyFiles", data: BytesLike): Result;
}

export namespace FileAddedEvent {
  export type InputTuple = [
    owner: AddressLike,
    cid: string,
    name: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    owner: string,
    cid: string,
    name: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    owner: string;
    cid: string;
    name: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FileRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): FileRegistry;
  waitForDeployment(): Promise<this>;

  interface: FileRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addFile: TypedContractMethod<
    [cid: string, name: string],
    [void],
    "nonpayable"
  >;

  getMyFiles: TypedContractMethod<
    [],
    [FileRegistry.FileRecordStructOutput[]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addFile"
  ): TypedContractMethod<[cid: string, name: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getMyFiles"
  ): TypedContractMethod<[], [FileRegistry.FileRecordStructOutput[]], "view">;

  getEvent(
    key: "FileAdded"
  ): TypedContractEvent<
    FileAddedEvent.InputTuple,
    FileAddedEvent.OutputTuple,
    FileAddedEvent.OutputObject
  >;

  filters: {
    "FileAdded(address,string,string,uint256)": TypedContractEvent<
      FileAddedEvent.InputTuple,
      FileAddedEvent.OutputTuple,
      FileAddedEvent.OutputObject
    >;
    FileAdded: TypedContractEvent<
      FileAddedEvent.InputTuple,
      FileAddedEvent.OutputTuple,
      FileAddedEvent.OutputObject
    >;
  };
}
