/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FileRegistry } from "./FileRegistry";
export * as factories from "./factories";
export { FileRegistry__factory } from "./factories/FileRegistry__factory";
